# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelavniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumPrvegaObiska', models.DateField()),
                ('nujnostObiska', models.CharField(choices=[('obvezen', 'obvezen'), ('okviren', 'okviren')], max_length=19)),
                ('steviloObiskov', models.IntegerField()),
                ('vrstaObiska', models.CharField(choices=[('preventivni obisk', 'preventivni obisk'), ('kurativni obisk', 'kurativni obisk')], max_length=29)),
                ('podVrstaObiska', models.CharField(choices=[('obisk nosečnice', 'obisk nosečnice'), ('obisk otročičnice in novorojenčka', 'obisk otročičnice in novorojenčka'), ('preventiva starostnika', 'preventiva starostnika'), ('aplikacija inekcije', 'aplikacija inekcije'), ('odvzem krvi', 'odvzem krvi'), ('kontrola zdravstvenega stanja', 'kontrola zdravstvenega stanja')], max_length=29)),
                ('casovniIntervalMedDvemaObiskoma', models.CharField(blank=True, max_length=25, null=True)),
                ('casovnoObdobje', models.CharField(blank=True, max_length=25, null=True)),
                ('datumVnosa', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='IzvajalecZdravstveneDejavnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeIzvajalecZdravstveneDejavnosti', models.CharField(max_length=250)),
                ('sifraIzvajalecZdravstveneDejavnosti', models.CharField(max_length=25)),
                ('naslovIzvajalecZdravstveneDejavnosti', models.CharField(default='string', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDelovniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilo', models.IntegerField()),
                ('delavniNalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.DelavniNalog')),
            ],
        ),
        migrations.CreateModel(
            name='Obisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predvidenDatumObiska', models.DateField()),
                ('dejanskiDatumObiska', models.DateField(default=django.utils.timezone.now)),
                ('zaporednoSteviloObiska', models.IntegerField(default=0)),
                ('delavniNalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.DelavniNalog')),
            ],
        ),
        migrations.CreateModel(
            name='Okolis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeOkolisa', models.CharField(max_length=250)),
                ('sifraOkolisa', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=250)),
                ('priimek', models.CharField(max_length=250)),
                ('zavarovanjeID', models.CharField(max_length=20)),
                ('datumRojstva', models.DateField()),
                ('spol', models.CharField(choices=[('M', 'moški'), ('Ž', 'ženska')], max_length=1)),
                ('naslov', models.CharField(max_length=250)),
                ('sorodstvoRacun', models.CharField(default='lasten', max_length=250)),
                ('okolisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Okolis')),
            ],
        ),
        migrations.CreateModel(
            name='PacientDelovniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delavniNalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.DelavniNalog')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Pacient')),
            ],
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imePosta', models.CharField(max_length=250)),
                ('sifraPosta', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RacunOsebje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osebaID', models.CharField(max_length=5)),
                ('geslo', models.CharField(default='blablabla', max_length=50)),
                ('geslo2', models.CharField(default='blablabla', max_length=50)),
                ('priimek', models.CharField(max_length=250)),
                ('ime', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=25)),
                ('vloga', models.CharField(choices=[('Zdravnik', 'Zdravnik'), ('Vodja PS', 'Vodja PS'), ('Medicinska sestra', 'Medicinska sestra'), ('Uslužbenec', 'Uslužbenec')], default='Zdravnik', max_length=40)),
                ('neuspesenVnos', models.IntegerField(default=0)),
                ('izvajalecZdravstveneDejavnosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.IzvajalecZdravstveneDejavnosti')),
            ],
        ),
        migrations.CreateModel(
            name='RacunPacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('geslo', models.CharField(default='blablabla', max_length=50)),
                ('geslo2', models.CharField(default='blablabla', max_length=50)),
                ('aktiviran', models.BooleanField(default=False)),
                ('imeKontaktna', models.CharField(blank=True, max_length=250, null=True)),
                ('priimekKontaktna', models.CharField(blank=True, max_length=250, null=True)),
                ('naslovKontaktna', models.CharField(blank=True, max_length=250, null=True)),
                ('telefonKontaktna', models.CharField(blank=True, max_length=25, null=True)),
                ('sorodstvoKontaktna', models.CharField(blank=True, max_length=250, null=True)),
                ('neuspesenVnos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SifrantBolezn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeBolezni', models.CharField(max_length=250)),
                ('sifraBolezni', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SifrantMateriala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barvaEpruvet', models.CharField(choices=[('rd', 'rdeča'), ('mo', 'modra'), ('ru', 'rumena'), ('ze', 'zelena')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SifrantZdravil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeZdravila', models.CharField(max_length=250)),
                ('sifraZdravila', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ZdravilaDelovniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilo', models.IntegerField()),
                ('delavniNalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.DelavniNalog')),
                ('zdravial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.SifrantZdravil')),
            ],
        ),
        migrations.AddField(
            model_name='pacient',
            name='posta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Posta'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='racun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.RacunPacient'),
        ),
        migrations.AddField(
            model_name='okolis',
            name='medicinskaSestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.RacunOsebje'),
        ),
        migrations.AddField(
            model_name='materialdelovninalog',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.SifrantMateriala'),
        ),
        migrations.AddField(
            model_name='izvajaleczdravstvenedejavnosti',
            name='posta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Posta'),
        ),
        migrations.AddField(
            model_name='delavninalog',
            name='bolezn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ps.SifrantBolezn'),
        ),
        migrations.AddField(
            model_name='delavninalog',
            name='izvajalecZdravstveneDejavnosti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.IzvajalecZdravstveneDejavnosti'),
        ),
        migrations.AddField(
            model_name='delavninalog',
            name='zdravnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.RacunOsebje'),
        ),
    ]
