# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obisk',
            name='obiskOpravljen',
            field=models.CharField(choices=[('ne', 'ne'), ('da', 'da')], default='ne', max_length=2),
        ),
        migrations.AddField(
            model_name='obisk',
            name='planiranDatumObiska',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='obisk',
            name='zePlaniran',
            field=models.CharField(choices=[('ne', 'ne'), ('da', 'da')], default='ne', max_length=2),
        ),
    ]
