# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0002_auto_20170412_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=250)),
            ],
        ),
    ]
