# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0005_auto_20170412_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racunpacient',
            name='casregistracije',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 14, 54, 28, 766522)),
        ),
    ]
