# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0012_auto_20170413_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='racunosebje',
            name='zadnjaPrijava',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 19, 4, 679403)),
        ),
        migrations.AddField(
            model_name='racunpacient',
            name='zadnjaPrijava',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 19, 4, 680907)),
        ),
        migrations.AlterField(
            model_name='racunpacient',
            name='casregistracije',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 19, 4, 680406), null=True),
        ),
    ]
