# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0013_auto_20170414_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='racunosebje',
            name='trenutnaPrijava',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 20, 55, 994283)),
        ),
        migrations.AddField(
            model_name='racunpacient',
            name='trenutnaPrijava',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 20, 55, 995833)),
        ),
        migrations.AlterField(
            model_name='racunosebje',
            name='zadnjaPrijava',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 20, 55, 994283)),
        ),
        migrations.AlterField(
            model_name='racunpacient',
            name='casregistracije',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 20, 55, 995314), null=True),
        ),
        migrations.AlterField(
            model_name='racunpacient',
            name='zadnjaPrijava',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 0, 20, 55, 995833)),
        ),
    ]
